## where to store your database, default is your system data directory
## linux/mac: ~/.local/share/atuin/history.db
## windows: %USERPROFILE%/.local/share/atuin/history.db
# db_path = "~/.history.db"

## where to store your encryption key, default is your system data directory
## linux/mac: ~/.local/share/atuin/key
## windows: %USERPROFILE%/.local/share/atuin/key
# key_path = "~/.key"

## where to store your auth session token, default is your system data directory
## linux/mac: ~/.local/share/atuin/session
## windows: %USERPROFILE%/.local/share/atuin/session
# session_path = "~/.session"

## date format used, either "us" or "uk"
# dialect = "us"

## default timezone to use when displaying time
## either "l", "local" to use the system's current local timezone, or an offset
## from UTC in the format of "<+|->H[H][:M[M][:S[S]]]"
# timezone = "local"

## enable or disable automatic sync
auto_sync = false

## enable or disable automatic update checks
# update_check = true

## address of the sync server
# sync_address = "https://api.atuin.sh"

## how often to sync history. note that this is only triggered when a command
## is ran, so sync intervals may well be longer
## set it to 0 to sync after every command
# sync_frequency = "10m"

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
# search_mode = "fuzzy"

## which filter mode to use by default
## possible values: "global", "host", "session", "session-preload", "directory", "workspace"
filter_mode = "host"

## which filter mode to use when atuin is invoked from a shell up-key binding
## the accepted values are identical to those of "filter_mode"
filter_mode_shell_up_key_binding = "directory"

## which search mode to use when atuin is invoked from a shell up-key binding
## the accepted values are identical to those of "search_mode"
# search_mode_shell_up_key_binding = "fuzzy"

## which style to use
## possible values: auto, full, compact
style = "compact"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 30

## Invert the UI - put the search bar at the top , Default to `false`
# invert = false

## enable or disable showing a preview of the selected command
# show_preview = true

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
# exit_mode = "return-original"

## possible values: emacs, subl
# word_jump_mode = "emacs"

## number of context lines to show when scrolling by pages
# scroll_context_lines = 1

## use ctrl instead of alt as the shortcut modifier key for numerical UI shortcuts
# ctrl_n_shortcuts = false

## default history list format - can also be specified with the --format arg
# history_format = "{time}\t{command}\t{duration}"

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
history_filter = [
  "^export ",
  "^AWS_",
  "^TOKEN=",
  "^SECRET=",
]

## prevent commands run with cwd matching any of these regexes from being written
## to history.
# cwd_filter = [
#   "^/very/secret/area",
# ]

## Configure the maximum height of the preview to show.
# max_preview_height = 4

## Configure whether or not to show the help row
# show_help = true

## Configure whether or not to show tabs for search and inspect
# show_tabs = true

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command.
## If set to false, both enter and tab will place the command in the prompt for editing.
enter_accept = false

## Defaults to true. If enabled, Atuin will not save it if we get a match
## against default secret patterns (AWS key, GitHub pat, Slack tokens, etc.)
# secrets_filter = true

## This specifies the keymap on the startup of `atuin search`.
## possible values: auto, emacs, vim-insert, vim-normal
# keymap_mode = "auto"

# network_connect_timeout = 5
# network_timeout = 5

## Timeout (in seconds) for acquiring a local database connection (sqlite)
# local_timeout = 5

[stats]
## Set commands where we should consider the subcommand for statistics.
# common_subcommands = [
#   "apt",
#   "cargo",
#   "docker",
#   "git",
#   "go",
#   "kubectl",
#   "nix",
#   "npm",
#   "systemctl",
#   "tmux",
# ]

## Set commands that should be totally stripped and ignored from stats
# common_prefix = ["sudo"]

## Set commands that will be completely ignored from stats
# ignored_commands = [
#   "cd",
#   "ls",
#   "vi"
# ]

[keys]
# scroll_exits = true

[sync]
records = true

[preview]
## possible values: auto, static, fixed
# strategy = "auto"

[daemon]
## Enables using the daemon to sync
# enabled = false
# sync_frequency = 300

# [theme]
# name = "autumn"
