---
- name: 'Install asdf'
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: "{{ home_dir }}/.asdf"
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Checkout the latest branch'
  shell:
    chdir: "{{ home_dir  }}/.asdf"
    cmd: 'git checkout "$(git describe --abbrev=0 --tags)"'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Change completion file permission'
  file:
    path: "{{ home_dir }}/.asdf/completions/asdf.bash"
    mode: '0755'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

